name: Deploy
on:
  push:
    branches:
      - main
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GH_FETCH_TOKEN: ${{ secrets.GH_FETCH_TOKEN }}

jobs:
  deploy:
    name: Deploy to the World-Net
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://kenny.wtf
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: 'latest'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: run deploy earthfile
        run: earthly --secret PULUMI_ACCESS_TOKEN="${{ secrets.PULUMI_ACCESS_TOKEN }}" --secret AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" --secret AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }} --secret GITHUB_TOKEN="${{ secrets.GH_FETCH_TOKEN }}" +deploy
